"""Relatório clássico offline com dados reais, sem publicar HTML no Git."""
import json, html
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import dlm_classico as c

def build(destination):
 m=pd.read_csv(c.OUT/'modelos.csv');cr=pd.read_csv(c.OUT/'cr2.csv');pf=pd.read_csv(c.OUT/'perfis_cr1.csv');boot=pd.read_csv(c.OUT/'bootstrap.csv');sup=pd.read_csv(c.OUT/'suporte_design.csv');st=pd.read_csv(c.OUT/'estacionariedade_resumo.csv')
 for per in ['Total','Pré']:
  for col in ['total_desastres','tipo_onda_de_frio','tipo_granizo']:
   p=cr[(cr.periodo==per)&(cr.coluna==col)&(cr.especificacao=='Principal')];fig,ax=plt.subplots(1,2,figsize=(11,4))
   for a,ep,title in zip(ax,['beta_','C_'],['Perfil incremental','Resposta acumulada do pulso']):
    z=p[p.endpoint.str.startswith(ep)].copy();z['lag']=z.endpoint.str.split('_').str[-1].astype(int);z=z.sort_values('lag');a.plot(z.lag,z.estimate,'o-',label='estimativa');a.fill_between(z.lag,z.low,z.high,alpha=.2,label='IC95% CR2 ponto a ponto');a.axhline(0,color='black',lw=.8);a.set(xlabel='Lag em meses',ylabel='pp por unidade de cobertura',title=title);a.legend(fontsize=8)
   fig.suptitle(c.r.label(col)+' — '+per+' — irrestrito 1..10');fig.tight_layout();fig.savefig(c.FIG/(per+'_'+col+'.svg'));plt.close(fig)
 def records(x):return json.loads(x.to_json(orient='records',force_ascii=False))
 payload=json.dumps(dict(m=records(m),cr=records(cr),p=records(pf),b=records(boot),s=records(sup)),ensure_ascii=False).replace('</','<\\/')
 source=r'''<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DLM clássico 1–10</title><style>body{font:17px/1.65 system-ui;background:#f3f6fa;color:#182335;max-width:1180px;margin:auto;padding:28px}section{background:white;padding:25px;margin:20px 0;border:1px solid #dce3ed;border-radius:12px}h1,h2{line-height:1.2}select,button{font:inherit;padding:8px;margin:5px}canvas{width:100%;height:340px}table{border-collapse:collapse;width:100%;font-size:14px}td,th{padding:8px;border-bottom:1px solid #dde4ee;text-align:left}.scroll{overflow:auto}.warning{border-left:5px solid #b35b21;padding-left:15px}small{color:#536174}</style>
 <h1>DLM clássico: defasagens de 1 a 10 meses</h1><p>Análise em painel estadual, sem spline, α=0,05. Cada lag recebe um coeficiente independente. Resultados anteriores preservados; este relatório não substitui a análise nacional complementar.</p>
 <section><h2>O que mudou?</h2><p>A autora solicitou DLM tradicional. O modelo estima ΔI<sub>it</sub> = α<sub>i</sub> + λ<sub>t</sub> + Σ β<sub>k</sub>X<sub>i,t−k</sub> + ε<sub>it</sub>. Principal: K=10, lags 1..10, exposição=Cobertura municipal relativa, UF+mês-ano FE, não ponderado. Os K 1..9 verificam sensibilidade, não foram escolhidos por significância. Com contemporâneo e ΔX são duas comparações metodológicas no K 10.</p><p>Todos modelos usam a mesma amostra por exposição/período: dezembro 2013 em diante; total 133 meses/3591 UF-mês e pré 74 meses/1998 UF-mês. Esse início respeita a disponibilidade de ΔX no lag 10, sem dados anteriores a 2013 inventados.</p></section>
 <section><h2>Estacionariedade e chaves repetidas</h2><p>ΔI apresenta evidência favorável no CIPS preservado, em ambos períodos. A taxa em nível é sensível ao determinístico/período. Exposições raras/constantes impediram CIPS anterior: indisponibilidade não confirma estacionariedade. ADF/KPSS por UF abaixo são diagnósticos complementares; não corrigem dependência transversal e não provam estacionariedade conjunta. Diferenciar X altera a pergunta para associação com mudança da cobertura; não torna esse modelo automaticamente equivalente.</p><p>Atlas:40339 registros,40238 chaves municipais únicas,101 linhas adicionais em chaves repetidas. A preserva tudo; B deduplica UF/município/data/COBRADE; C conta municípios distintos. Verificação confirmou cobertura idêntica antes/depois de deduplicar. A cópia local truncada foi substituída pelo anexo íntegro antes da estimação.</p>STATIONARITY</section>
 <section><h2>Escolha o resultado para entender</h2><label>Período <select id="period"></select></label><label>Exposição <select id="expo"></select></label><label>Desenho <select id="spec"></select></label><label>K <select id="lag"></select></label><div id="text"></div><canvas id="beta" width="1100" height="340"></canvas><canvas id="cum" width="1100" height="340"></canvas><p id="caption"></p><button id="download">Baixar tabela selecionada CSV</button><div class="scroll"><table id="tab"></table></div></section>
 <section><h2>Resultados observados desta execução</h2><p>PrincipalK 10: um acumulado nominal CR 2 a 5% — Estiagem e Seca no pré (p=0,040841; q BH=0,951156); nenhum após BH. BootstrapK 10: dois acumulados nominais (Climatológico pré e Estiagem/Seca pré), nenhum após BH; nenhum conjunto nominal. CR 2 conjunto:9 calculados e 37 indisponíveis no principal, não 37 resultados nulos.</p><p>Nos 460 modelos da grade, cluster convencional teve 51 acumulados nominais e 13 após BH 480 (repetições de Calor/Baixa Umidade total K 8/9, Frio total K 3..10 eTornado pré K 3..5). São resultados exploratórios CR 1 S: CR 2/bootstrap foram calculados paraK 10, não para cada horizonte. Não apresentar 13 como 13 categorias independentes. BIC preferiuK 1 em 45 cenários eK 6 emum; isso não demonstra duração de 1 mês.</p></section><section><h2>Por que bootstrap? Por que painel e nacional?</h2><p>Wild bootstrap é um método de inferência sobre o mesmo DLM: não é outro modelo da relação substantiva. Ele impõe H 0, multiplica resíduos por pesos de UF e reestima para aproximar a distribuição do teste. Há 27 UFs, mas algumas exposições concentram a informação em muito poucas. Bootstrap e CR 2 verificam se o p convencional é confiável; nenhum deles cria suporte ausente.</p><p>O painel reúne UFs e meses, controla choques nacionais por FE e identifica exposição relativa entre estados. O nacional usa 100 ×ΣCI/ΣCA e exposição nacional; mantém variação comum removida pelo painel, porém é mais vulnerável a confundimento agregado. O painel é principal; o nacional anterior é complementar e não foi reestimado nesta extensão clássica.</p></section>
 <section><h2>Como interpretar p, curvas e limites</h2><p>α=0,05 é o limiar, não um p-valor fixado. p nominal&lt;0,05 é rejeição sem ajuste; q BH&lt;0,05 é rejeição após multiplicidade. Famílias 48 por K/desenho/endpoint; grade 480 adicional para comparação exploratória dos dez K. Não se escolheu o menor p. IC ponto a ponto não é banda simultânea.</p><p>βk mede a associação com ΔI no horizontek para um pulso isolado. C(h)=Σβk mede a mudança acumulada na taxa sob o modelo. Exposição persistente combina pulsos; a soma não é a mesma resposta de uma mudança permanente. Um ponto de curva cruzar zero não comprova reversão ou duração. Cobertura mede municípios registrados, não população/intensidade. ΔX muda o estimando: acumulado de coeficientes refere-se a pulso em ΔX, não pulso isolado em X.</p></section>
 <section><h2>Execução e rastreabilidade</h2><p>Notebook 19 e módulos próprios; fontes anteriores inalteradas. CR 2 em R clubSandwich com comparação dos coeficientes Python/R. Bootstrap principal K 10 com 4999/9999 sorteios e checagem de rank. Arquivos incluem métricas de suporte, metadados, covariância aplicada aos contrastes, versões e testes. Granger e SARIMAX não executados.</p></section>
 <script>const D=PAYLOAD;const $=id=>document.getElementById(id),fmt=x=>x==null?'indisponível':Number(x).toLocaleString('pt-BR',{maximumSignificantDigits:5});
 function options(el,a){el.innerHTML='';a.forEach(v=>{let o=document.createElement('option');o.value=v;o.textContent=v;el.appendChild(o)})}
 options($('period'),['Total','Pré']);const cols=[...new Map(D.m.map(x=>[x.coluna,x.exposicao])).entries()];cols.forEach(([v,t])=>{let o=document.createElement('option');o.value=v;o.textContent=t;$('expo').appendChild(o)});options($('spec'),['Principal','Com contemporâneo','Delta X']);options($('lag'),[1,2,3,4,5,6,7,8,9,10]);$('lag').value='10';
 function plot(id,z,key,lo,hi,title){let a=$(id),c=a.getContext('2d'),W=a.width,H=a.height;c.clearRect(0,0,W,H);let vals=z.flatMap(r=>[r[key],r[lo],r[hi]]).filter(x=>x!=null),min=Math.min(0,...vals),max=Math.max(0,...vals);if(max==min)max=min+1;let pad=(max-min)*.08;min-=pad;max+=pad;let x=k=>80+(k-1)/(Math.max(2,z.length)-1)*(W-120),y=v=>H-55-(v-min)/(max-min)*(H-100);c.strokeStyle='#bbb';c.beginPath();c.moveTo(70,y(0));c.lineTo(W-35,y(0));c.stroke();c.font='16px system-ui';c.fillStyle='#192c49';c.fillText(title,70,25);c.fillText('Lag/horizonte em meses',W/2-100,H-10);c.fillText(fmt(max),5,45);c.fillText(fmt(min),5,H-50);z.forEach((r,i)=>{let xx=x(i+1);c.fillText(r.lag,xx-4,H-33);if(r[lo]!=null&&r[hi]!=null){c.strokeStyle='#7189a8';c.beginPath();c.moveTo(xx,y(r[lo]));c.lineTo(xx,y(r[hi]));c.stroke()}c.fillStyle='#173f75';c.beginPath();c.arc(xx,y(r[key]),4,0,Math.PI*2);c.fill()});c.strokeStyle='#173f75';c.beginPath();z.forEach((r,i)=>i?c.lineTo(x(i+1),y(r[key])):c.moveTo(x(i+1),y(r[key])));c.stroke()}
 function update(){let per=$('period').value,col=$('expo').value,spec=$('spec').value;if(spec!='Principal')$('lag').value='10';$('lag').disabled=spec!='Principal';let K=Number($('lag').value),match=r=>r.periodo==per&&r.coluna==col&&r.especificacao==spec&&r.K==K,m=D.m.find(match);if(!m){$('text').textContent='Não estimável na triagem prévia: sem resultado calculado.';['beta','cum'].forEach(id=>$(id).getContext('2d').clearRect(0,0,1100,340));$('tab').innerHTML='';$('caption').textContent='Sem curva estimada para este cenário.';return}let cr=D.cr.filter(match),jc=cr.find(r=>r.endpoint=='joint'),acc=cr.find(r=>r.endpoint=='acumulado'),b=D.b.find(r=>match(r)&&r.endpoint=='acumulado'),s=D.s.find(match);let z=D.p.filter(match).sort((a,b)=>a.lag-b.lag),method='CR1S';if(cr.length){method='CR2 / Satterthwaite';z=z.map(r=>{let bb=cr.find(a=>a.endpoint=='beta_'+r.lag),cc=cr.find(a=>a.endpoint=='C_'+r.lag);return {...r,beta:bb.estimate,beta_low:bb.low,beta_high:bb.high,C:cc.estimate,C_low:cc.low,C_high:cc.high}})}
 let p=acc?acc.p:m.acumulado_p,q=acc?acc.q:m.q_acumulado_p,est=acc?acc.estimate:m.acumulado_estimate,low=acc?acc.low:m.acumulado_low,high=acc?acc.high:m.acumulado_high;let decision=p==null?'Inferência indisponível':p<.05?'Rejeição nominal a 5%':'Sem rejeição nominal a 5%';let adjusted=q==null?'Ajuste não calculado':q<.05?'Rejeição após BH':'Sem rejeição após BH';let scenario=spec=='Delta X'?'um pulso de+10pp na mudança da cobertura':'um pulso isolado de+10pp de cobertura';
 $('text').innerHTML=`<p><b>Pergunta:</b> ${m.exposicao}, ${per}: como a exposição registrada ${spec=='Delta X'?'em mudança':'em nível'} entre ${m.lag_inicio} e ${K} meses antes se associa aΔI?</p><p><b>Amostra:</b> ${m.N} UF-mês,${m.ufs} UFs,${m.data_inicio} a${m.data_fim}. ${m.n_parametros_exposicao} coeficientes livres; nenhum spline. UF+mês-anoFE.</p><p><b>Acumulado:</b> ${fmt(est)} pp/unidade; IC95% ${method} [${fmt(low)};${fmt(high)}]; p=${fmt(p)}; q BH=${fmt(q)}. ${spec=='Principal'?'q da grade480/CR1S='+fmt(m.q_grade_acumulado_p)+'.':''} ${decision}; ${adjusted}. ${acc?'df='+fmt(acc.df):'CR2 não foi recalculado para K1..9; comparação CR1S.'}</p><p><b>Teste conjunto:</b> p=${fmt(jc?jc.p:m.joint_acumulado_p)}; q=${fmt(jc?jc.q:m.q_joint_acumulado_p)}; ${jc?jc.status:'CR1S comparativo'}. Conjunto indisponível não é nulo.</p><p><b>Escala ilustrativa:</b> ${scenario}: ${fmt(est*.1)}pp, IC[${fmt(low*.1)};${fmt(high*.1)}]. Verifique plausibilidade para categorias raras; ΔX não equivale à mesma intervenção em nível.</p><p class="warning"><b>Suporte:</b> ${s.ufs_janela} UFs com cobertura na janela, número efetivo por contraste${fmt(s.neff_contraste)}, concentração top1${fmt(s.top1_contraste*100)}%; ${s.status_suporte}. ${b?'Bootstrap: p='+fmt(b.p)+'; q='+fmt(b.q_p)+'; B='+b.B+'.':'Bootstrap não executado nesta sensibilidade.'} Não rejeitar não demonstra ausência de associação ou equivalência.</p>`;
 plot('beta',z,'beta','beta_low','beta_high','βk: pp por unidade de exposição — '+method);plot('cum',z,'C','C_low','C_high','C(h): acumulado em pp — '+method);$('caption').textContent='Cada ponto usa covariâncias completas; barras são IC95% ponto a ponto, não bandas simultâneas. Sinal e mudanças da curva são estimativas sujeitas à incerteza e ao suporte. O último lag significativo não mede duração.';$('tab').innerHTML='<tr><th>Lag</th><th>β</th><th>IC β</th><th>C(h)</th><th>IC C(h)</th></tr>'+z.map(r=>`<tr><td>${r.lag}</td><td>${fmt(r.beta)}</td><td>[${fmt(r.beta_low)};${fmt(r.beta_high)}]</td><td>${fmt(r.C)}</td><td>[${fmt(r.C_low)};${fmt(r.C_high)}]</td></tr>`).join('');$('download').onclick=()=>{let csv='lag,beta,beta_low,beta_high,C,C_low,C_high\n'+z.map(r=>[r.lag,r.beta,r.beta_low,r.beta_high,r.C,r.C_low,r.C_high].join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='dlm_classico_selecionado.csv';a.click();URL.revokeObjectURL(a.href)}}
 ['period','expo','spec','lag'].forEach(id=>$(id).onchange=update);update();</script></html>'''
 source=source.replace('PAYLOAD',payload).replace('STATIONARITY','<div class="scroll">'+st[st.serie.isin(['I','total_desastres','grupo_climatologico','grupo_hidrologico','grupo_meteorologico','tipo_onda_de_frio'])].to_html(index=False,border=0)+'</div>')
 Path(destination).write_text(source,encoding='utf-8');return Path(destination)

if __name__=='__main__':
 print(build(c.ROOT.parent/'relatorio_dlm_classico_1a10.html'))
