"""Apresenta novos DLMs selecionados e mantém relatório anterior como histórico explícito."""
from pathlib import Path
import argparse,json,re
import pandas as pd
import relatorio_granger_dlm as old
ROOT=Path(__file__).resolve().parents[1]
CSS='''
.current-metric{min-width:0;overflow-wrap:anywhere}.current-equation{overflow-x:auto}.current-summary{border-top:5px solid #168878}.current-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.current-metric{padding:18px;background:#eef5f9;border:1px solid #d4e3ed;border-radius:12px}.current-metric strong{display:block;font-size:28px;color:#1e5c78}.current-metric span{font-size:13px}.current-signal{padding:22px;border-left:5px solid #168878;background:#eef8f4;margin:14px 0;border-radius:12px}.current-controls{position:sticky;top:0;z-index:10;display:flex;flex-wrap:wrap;gap:14px;background:white;padding:18px;border:1px solid #cddfe9;border-top:4px solid #168878;border-radius:12px;box-shadow:0 4px 20px #1232}.current-interpretation{background:#edf5fa;padding:20px;border-left:4px solid #4e8eb3;border-radius:10px;margin:20px 0}.current-interpretation p{margin:8px 0}.selection-row{display:grid;grid-template-columns:2fr repeat(4,1fr);min-width:850px}.selection-row>div{padding:10px;border-bottom:1px solid #dce5ed;font-size:13px;background:#f2f6f9}.selection-row .head{background:#1b435c;color:white;font-weight:600}.selection-row .rejected{background:#dff2e8}.selection-row .na{background:#eeeeef;color:#697886}.current-legacy{background:#fff8ee;border:2px solid #dbc6a4;padding:22px}.current-legacy>summary{font-size:20px}.current-legacy header{display:none}.current-legacy main{padding:0}.current-legacy .filters{position:relative}.current-legacy section{scroll-margin-top:30px}.lag-choice{font-size:36px;color:#1d6376;font-weight:700}.current-warning{padding:15px;border-left:4px solid #b58443;background:#fff5e5;margin:18px 0}.current-equation math{font-size:22px;margin:20px 0}@media(max-width:500px){.current-metric strong{font-size:21px}.current-controls label{width:100%;min-width:0}.current-controls select{width:100%;min-width:0;max-width:100%}}@media(max-width:800px){.current-metrics{grid-template-columns:repeat(2,1fr)}.current-controls{position:relative}}@media print{.current-controls{position:static}.current-legacy{display:none}}
'''
BODY='''<main id="current-report"><nav><a href="#current-summary">Resultados atuais</a><a href="#current-method">Seleção de defasagens</a><a href="#current-explore">Explorar</a><a href="#current-map">Comparar categorias</a><a href="#current-granger">Granger</a><a href="#historical-report">Análises anteriores</a></nav>
<section id="current-summary" class="current-summary"><h2>Resultados atuais: DLMs com janela selecionada por desastre e período</h2><div class="current-metrics" id="current-counts"></div><p>Os dois DLMs atuais usam coeficientes livres e lags de 1 até K, sem spline. O BIC seleciona K separadamente para cada exposição e período. O nacional também seleciona as defasagens próprias da inadimplência. O Granger está preservado, sem nova estimação.</p><div class="current-warning"><b>Inferência condicional à seleção:</b> os p-valores, IC e bootstrap abaixo condicionam ao K escolhido. Não incorporam toda a incerteza da seleção de K ou dos lags próprios. BH corrige a família de testes, mas não essa seleção. Os sinais continuam exploratórios.</div><h3>Acumulados nacionais que permanecem após BH/HAC</h3><div id="current-signals"></div><p>Outros inclui fenômenos naturais não diretamente climáticos e eventos tecnológicos/antrópicos. O sinal dessa tipologia não pode ser usado como evidência específica de mudanças climáticas. Inundações e Onda de Frio, significativas no nacional antigo com spline, não permanecem após BH no nacional clássico selecionado atual.</p><details><summary>Todos os testes conjuntos nacionais significativos</summary><p>O teste conjunto avalia o perfil inteiro; o acumulado avalia a soma. Um pode rejeitar sem o outro. As famílias BH48 são separadas por endpoint.</p><div class="scroll" id="current-joint"></div></details></section>
<section id="current-method"><h2>Como a janela foi escolhida</h2><div class="grid"><div class="note"><b>Painel</b><p>Para cada desastre e período, comparar K=1,…,10 pelo BIC em amostra comum. Todos os modelos incluem FE de UF e mês-ano; dependente ΔI e exposição em cobertura estadual.</p><p>Recalcular CR2/Satterthwaite e wild cluster bootstrap restrito por UF (4.999 sorteios) para o modelo selecionado. O teste conjunto é bootstrap; não é HTZ.</p></div><div class="note"><b>Nacional</b><p>Comparar conjuntamente K=1,…,10 e AR=0,1,2 pelo BIC em amostra comum. Incluir sazonalidade e tendência; dependente ΔI ponderada pelas carteiras e exposição em cobertura nacional.</p><p>Recalcular HAC12 e verificar estabilidade AR e autocorrelação residual. A soma direta não inclui propagação autorregressiva.</p></div></div><p>Para investigar a associação entre exposição local e inadimplência, o painel continua sendo a análise principal: compara a variação dentro de cada UF e controla choques comuns de cada mês. O nacional é complementar: resume o Brasil, pondera a taxa pelas carteiras e controla a dinâmica da inadimplência, mas não separa choques nacionais omitidos com a mesma flexibilidade. A escolha do principal não depende de qual modelo produz significância.</p><p><b>Não se escolhe um único lag isolado:</b> K=5 significa incluir os meses 1, 2, 3, 4 e 5. Cada coeficiente descreve um horizonte. K selecionado não é a duração comprovada da associação, e categorias distintas podem selecionar o mesmo K.</p><div class="current-equation"><math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mo>Δ</mo><msub><mi>I</mi><mi>it</mi></msub><mo>=</mo><msub><mi>α</mi><mi>i</mi></msub><mo>+</mo><msub><mi>λ</mi><mi>t</mi></msub><mo>+</mo><munderover><mo>∑</mo><mrow><mi>k</mi><mo>=</mo><mn>1</mn></mrow><msub><mi>K</mi><mrow><mi>c</mi><mo>,</mo><mi>r</mi></mrow></msub></munderover><msub><mi>β</mi><mrow><mi>c</mi><mo>,</mo><mi>r</mi><mo>,</mo><mi>k</mi></mrow></msub><msub><mi>X</mi><mrow><mi>c</mi><mo>,</mo><mi>i</mi><mo>,</mo><mi>t</mi><mo>−</mo><mi>k</mi></mrow></msub><mo>+</mo><msub><mi>ε</mi><mi>it</mi></msub></mrow></math><p class="caption">Painel: c identifica a categoria e r o período. Um ajuste separado por combinação, com a janela K selecionada. Não é um modelo contendo todas as categorias simultaneamente.</p></div><div id="current-K-summary" class="current-metrics"></div><p>AIC aparece como comparação, sem trocar o critério principal conforme a significância. ΔBIC contra o modelo sem exposição é calculado mantendo os controles e AR: negativo favorece incluir exposição; positivo favorece o comparador sem exposição. Mesmo o melhor DLM da grade pode não superar esse comparador.</p></section>
<div class="current-controls" id="current-explore"><label>Período<select id="sel-period"><option value="Total">Total • 2013–2024</option><option value="Pré">Pré-pandemia • até jan/2020</option></select></label><label>Nível<select id="sel-level"><option>Total</option><option>Grupo</option><option>Tipologia</option><option value="Analítica">Agregado analítico</option></select></label><label>Exposição<select id="sel-exposure"></select></label><button id="sel-export">Baixar resultados CSV</button><button onclick="window.print()">Imprimir / salvar PDF</button></div>
<section><h2>Resultado selecionado</h2><p id="sel-title" class="selected"></p><div class="tabbuttons"><button data-current-tab="Painel" class="active">Painel selecionado</button><button data-current-tab="Nacional">Nacional selecionado</button></div>
<div id="selected-Painel"><h3>Painel clássico — janela própria por categoria e período</h3><div id="sel-panel-metrics" class="current-metrics"></div><div id="sel-panel-text" class="current-interpretation"></div><div class="grid"><div><div class="chart"><canvas id="sel-panel-beta" width="700" height="390"></canvas></div><p class="caption">β por lag, pp por unidade de cobertura estadual; IC95% CR2 ponto a ponto. A curva mostra estimativas condicionais aos demais lags e controles.</p></div><div><div class="chart"><canvas id="sel-panel-C" width="700" height="390"></canvas></div><p class="caption">C(h) acumula os coeficientes desde o lag 1, usando sua covariância completa. IC ponto a ponto, sem correção simultânea.</p></div></div><div id="sel-panel-support"></div><details><summary>Coeficientes, acumulados e inferência completa</summary><div class="scroll" id="sel-panel-table"></div></details><h3>Seleção da janela</h3><div class="chart"><canvas id="sel-panel-bic" width="1100" height="330"></canvas></div><p class="caption">Diferença do BIC de cada candidato contra o menor BIC da grade. Zero identifica a escolha principal; todos usam a mesma amostra.</p><details><summary>Grade de candidatos do painel</summary><div class="scroll" id="sel-panel-grid"></div></details></div>
<div id="selected-Nacional" class="hidden"><h3>Nacional clássico — sem spline, K e AR selecionados</h3><div id="sel-national-metrics" class="current-metrics"></div><div id="sel-national-text" class="current-interpretation"></div><div class="grid"><div><div class="chart"><canvas id="sel-national-beta" width="700" height="390"></canvas></div><p class="caption">Coeficientes livres de cobertura nacional por lag; IC95% HAC12 ponto a ponto. O contemporâneo foi excluído desta especificação atual.</p></div><div><div class="chart"><canvas id="sel-national-C" width="700" height="390"></canvas></div><p class="caption">Soma direta até cada horizonte, sem propagação AR. Significância ajustada da soma final não demonstra significância em um mês isolado.</p></div></div><details><summary>Coeficientes e acumulados nacionais</summary><div class="scroll" id="sel-national-table"></div></details><h3>Seleção conjunta de K e AR</h3><div class="chart"><canvas id="sel-national-bic" width="1100" height="330"></canvas></div><p class="caption">Para cada K, mostra o menor BIC entre AR0–2. A tabela expõe os 30 candidatos e a opção selecionada.</p><details><summary>Grade nacional completa</summary><div class="scroll" id="sel-national-grid"></div></details></div></section>
<section id="current-map"><h2>Janelas e decisões por categoria</h2><p>A visão acompanha o nível selecionado e inclui os dois períodos. Resultado não estimável continua visível. p e q são condicionais à seleção; não se confundem com probabilidade de existir efeito.</p><div class="scroll" id="selection-overview"></div></section>
<section id="current-granger"><h2>Granger preservado: resultado da categoria selecionada</h2><p>Triagem ampliada é a combinação dos diagnósticos de estacionariedade, resíduos, estabilidade e especificação examinados no Granger. Não é “triagem ilimitada”, nem garantia de causalidade. Rejeição BH e triagem são critérios distintos.</p><div id="sel-g-metrics" class="current-metrics"></div><div id="sel-g-text" class="current-interpretation"></div><div class="chart"><canvas id="sel-g-plot" width="1100" height="360"></canvas></div><p class="caption">Coeficientes na escala transformada e IC95% HAC ponto a ponto; BH42 pertence ao teste conjunto dos lags 1–3. Não é aumento direto da taxa em nível por registro adicional.</p><details><summary>Todos os dez sinais BH de Granger</summary><div class="scroll" id="sel-g-all"></div></details></section>
<section><h2>Conclusão da revisão de defasagens</h2><p>O ajuste agora usa uma janela selecionada para cada exposição e período, sem forçar escolhas distintas. No painel, predomina K1 e não há acumulado BH/CR2 ou BH/bootstrap. No nacional, três acumulados e seis testes conjuntos rejeitam após BH/HAC condicional; as direções não são uniformes e Outros não é exclusivamente climático.</p><p>Esses resultados não demonstram duração física, ausência de associação nas categorias sem rejeição, efeito causal ou atribuição ao aquecimento global. Há limitações de estacionariedade, suporte geográfico, autocorrelação em UFs, possíveis choques omitidos e incerteza de seleção. As sensibilidades de influência e placebos dos modelos antigos não são novas validações desses DLMs selecionados.</p><details><summary>Fontes e validação desta execução</summary><div class="scroll" id="selected-manifest"></div><p id="selected-validation"></p></details></section></main>
'''
JS=r'''
const S=JSON.parse(document.getElementById('selected-data').textContent);
function sm(label,value,note){return '<div class="current-metric"><span>'+esc(label)+'</span><strong>'+esc(value)+'</strong><span>'+esc(note||'')+'</span></div>'}
function selectedChoices(){let level=$('sel-level').value,cols=S.cobertura.filter(r=>r.nivel==level),unique=[...new Map(cols.map(r=>[r.coluna,r])).values()];$('sel-exposure').innerHTML=unique.map(r=>'<option value="'+esc(r.coluna)+'">'+esc(r.exposicao)+'</option>').join('')}
function selectedModel(name,per,col){let isPanel=name=='Painel',key=isPanel?'painel':'nacional',prefix=isPanel?'sel-panel':'sel-national',m=S[key].find(r=>r.periodo==per&&r.coluna==col),z=S[key+'_perfis'].filter(r=>r.periodo==per&&r.coluna==col),grid=S[key+'_candidatos'].filter(r=>r.periodo==per&&r.coluna==col);
 if(!m){$(prefix+'-metrics').innerHTML=sm('Estimabilidade','Indisponível','Triagem prévia; não é resultado nulo');$(prefix+'-text').innerHTML='<p>Não há modelo estimável nesta categoria e período. Não é possível atribuir direção ou duração à associação.</p>';['beta','C','bic'].forEach(id=>canvasEmpty(prefix+'-'+id,'Sem modelo estimado'));[prefix+'-table',prefix+'-grid'].forEach(id=>$(id).innerHTML='');if(isPanel)$('sel-panel-support').innerHTML='';return}
 $(prefix+'-metrics').innerHTML=sm('Janela BIC','1–'+m.K+' meses',m.K+' coeficientes livres; sem spline')+sm('Acumulado ajustado','q = '+f(m.q),'p = '+f(m.p)+' • '+(isPanel?'CR2':'HAC12'))+sm('Teste conjunto','q = '+f(m.q_joint),isPanel?'Wild bootstrap por UF':'HAC12 • AR('+m.p_proprio+')')+sm('Comparação sem exposição','ΔBIC = '+f(m.delta_BIC_sem_exposicao),m.delta_BIC_sem_exposicao<0?'Favorece incluir exposição':'Favorece modelo sem exposição');
 let peak=[...z].sort((a,b)=>Math.abs(b.beta)-Math.abs(a.beta))[0],direction=m.estimate>=0?'aumento':'redução',sig=m.q<.05,unit=isPanel?.01:1/5570,unitwords=isPanel?'um pulso de +1 ponto percentual de cobertura estadual':'um município adicional com registro entre os 5.570 municípios do Brasil';
 $(prefix+'-text').innerHTML='<b>O que esse resultado significa?</b><p>'+esc(m.exposicao)+' em '+per+': o BIC selecionou incluir os registros de '+(m.K==1?'um mês antes':'um a '+m.K+' meses antes')+'. '+(isPanel?'A associação é estimada descontando diferenças permanentes entre UFs e choques comuns de cada mês.':'A associação é estimada considerando a tendência, a sazonalidade e '+m.p_proprio+' lag(s) da própria inadimplência.')+'</p><p>A soma pontual dos coeficientes é '+(m.estimate>=0?'positiva':'negativa')+'. Para '+unitwords+', isolado em um mês, corresponde a '+direction+' de '+f(Math.abs(m.estimate*unit))+' ponto percentual no componente acumulado entre o mês seguinte e o mês '+m.K+'; IC95% ['+f(m.low*unit)+'; '+f(m.high*unit)+']. '+(sig?'O teste da soma permanece significativo após BH condicional à janela escolhida. Isso é compatível com '+direction+' nesse componente, sem identificar efeito causal.':'A soma não permanece significativa após BH; a direção pontual não é suficiente para afirmar aumento ou redução.')+' '+(!isPanel?'A soma direta não inclui a propagação autorregressiva.':'')+'</p><p>A maior magnitude mensal pontual está no '+peak.lag+'º mês após o registro ('+f(peak.beta*unit)+' pp nesse cenário). A rejeição da soma não prova que esse mês isoladamente seja significativo, nem que a associação comece ou termine nele.</p><p><b>Diagnósticos:</b> '+esc(m.diagnostico.replace('suporte suporte','suporte'))+'. '+(isPanel?'q bootstrap acumulado='+f(m.q_boot)+'; p='+f(m.p_boot)+'. ':'')+' '+(m.delta_BIC_sem_exposicao>=0?'Mesmo o melhor DLM da grade não superou o BIC do modelo sem exposição, o que limita a leitura substantiva desse perfil.':'O BIC da grade favorece exposição contra o comparador com os mesmos controles.')+'</p><p>Inferência condicional à seleção; os intervalos não são bandas simultâneas. '+(col=='tipo_outros'||col.startsWith('analitica_')?'Esta categoria exige cuidado taxonômico e não equivale automaticamente a desastre climático.':'')+'</p>';
 plot(prefix+'-beta',z,'lag','beta','beta_low','beta_high','βk • '+(isPanel?'CR2':'HAC12')+' • pp/unidade');plot(prefix+'-C',z,'lag','C','C_low','C_high','C(h) • soma direta • IC95%');
 table(prefix+'-table',z,[['lag','Lag'],['beta','β'],['beta_low','IC β baixo'],['beta_high','IC β alto'],['beta_p','p β nominal'],['C','C(h)'],['C_low','IC C baixo'],['C_high','IC C alto']]);
 let best=[];for(let k=1;k<=10;k++){let candidates=grid.filter(r=>r.K==k).sort((a,b)=>a.BIC-b.BIC);if(candidates.length)best.push({...candidates[0],delta:candidates[0].BIC-m.BIC})}plot(prefix+'-bic',best,'K','delta','none','none','ΔBIC para o melhor candidato');table(prefix+'-grid',grid,[['K','K'],['p_proprio','AR'],['N','N comum'],['BIC','BIC'],['AIC','AIC'],['selecionado','Selecionado']]);
 if(isPanel)$('sel-panel-support').innerHTML='<div class="current-metrics">'+sm('UFs expostas na janela',String(m.ufs_janela),'Em algum lag selecionado')+sm('N efetivo do contraste',f(m.neff_contraste),m.status_suporte)+sm('UF dominante',m.uf_dominante,pct(m.top1_contraste)+' da informação')+sm('df CR2',f(m.df),'Específico da soma')+'</div><p class="caption">Ljung–Box nominal rejeita em '+m.ufs_lb12_nominal+' UFs. É diagnóstico descritivo, sem ajuste conjunto entre UFs; não se trocou a janela para melhorar p.</p>';
}
function selectedUpdate(){let per=$('sel-period').value,col=$('sel-exposure').value,level=$('sel-level').value,meta=S.cobertura.find(r=>r.coluna==col);$('sel-title').textContent=perName(per)+' • '+meta.exposicao;selectedModel('Painel',per,col);selectedModel('Nacional',per,col);
 let gname=col=='total_desastres'?'Total nacional':meta.exposicao,g=D.gm.find(r=>r['Período']==perName(per)&&r['Exposição']==gname),gz=g?D.gc.filter(r=>r['Período']==g['Período']&&r['Exposição']==gname&&r['Especificação']==g['Especificação']):[];
 $('sel-g-metrics').innerHTML=sm('Granger principal',finite(g?.p)?'q = '+f(g['p BH']):'Indisponível','Teste conjunto HAC12 / BH42')+sm('Defasagens','1–3 meses','Dependente: lags 1,2,3,12')+sm('Triagem ampliada',finite(g?.p)?(g['Triagem ampliada']?'Favorável':'Com ressalvas'):'—','Qualidade diagnóstica')+sm('Reestimação','Preservado','Nenhum Granger reexecutado');
 $('sel-g-text').innerHTML=finite(g?.p)?'<p>'+ (g['p BH']<.05?'Os registros de um a três meses antes acrescentam informação preditiva na equação principal após BH42.':'Não há rejeição após BH42 para informação preditiva do conjunto de lags nesta equação.')+' A inadimplência e os registros são diferenciados mensal e sazonalmente; não é um aumento direto da taxa em nível por registro adicional.</p><p>Ressalvas: '+esc(g.Motivos||'sem indicação nos critérios examinados')+'. '+(col=='tipo_granizo'&&per=='Total'?'Granizo é sensível à inferência clássica/HC3 e ao BIC, apesar da triagem favorável no principal.':'')+'</p>':'<p>Teste não disponível para este cenário; não equivale a ausência de associação.</p>';plot('sel-g-plot',gz,'Lag','Coeficiente','IC baixo','IC alto','Granger preservado • IC95% HAC');
 let overview=[];for(let nm of ['painel','nacional'])for(let p of ['Pré','Total']){let planned=S.cobertura.filter(r=>r.desenho==(nm=='painel'?'Painel':'Nacional')&&r.periodo==p&&r.nivel==level);for(let r of planned){let m=S[nm].find(x=>x.periodo==p&&x.coluna==r.coluna);overview.push({desenho:r.desenho,periodo:p,exposicao:r.exposicao,K:m?.K,AR:m?.p_proprio,q:m?.q,q_joint:m?.q_joint,status:r.status,diagnostico:m?.diagnostico})}}
 table('selection-overview',overview,[['desenho','DLM'],['periodo','Período'],['exposicao','Categoria'],['K','K selecionado'],['AR','AR'],['q','q acumulado'],['q_joint','q conjunto'],['status','Estimabilidade'],['diagnostico','Diagnóstico']]);}
$('sel-level').onchange=()=>{selectedChoices();selectedUpdate()};['sel-period','sel-exposure'].forEach(id=>$(id).onchange=selectedUpdate);document.querySelectorAll('[data-current-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-current-tab]').forEach(x=>x.classList.toggle('active',x==b));['Painel','Nacional'].forEach(n=>$('selected-'+n).classList.toggle('hidden',n!=b.dataset.currentTab))});
$('current-counts').innerHTML=sm('Modelos selecionados','92','46 painel + 46 nacional')+sm('Painel • acumulados BH','0','CR2 e bootstrap')+sm('Nacional • acumulados BH','3','HAC12 condicional')+sm('Granger • rejeições BH','10','Preservadas; 1 com triagem favorável');
$('current-K-summary').innerHTML=sm('Painel • K=1','45 / 46','Alagamentos pré: K=6')+sm('Nacional • K=1','42 / 46','Demais: K2, K3, K5 e K8')+sm('Grade do painel','460','10 candidatos por cenário estimável')+sm('Grade nacional','1.380','10 K × 3 AR por cenário estimável');
$('current-signals').innerHTML=S.nacional.filter(r=>r.q<.05).map(r=>'<article class="current-signal"><h3>'+esc(r.exposicao)+' • '+r.periodo+'</h3><div class="lag-choice">1–'+r.K+' meses</div><p><b>Associação acumulada '+(r.estimate>0?'positiva':'negativa')+'</b> • q BH='+f(r.q)+'. '+(r.estimate>0?'Compatível com aumento':'Compatível com redução')+' no componente direto somado nessa janela, condicionado ao modelo selecionado. Não demonstra causalidade.</p><p>C(K)='+f(r.estimate)+' pp/unidade; IC95% ['+f(r.low)+'; '+f(r.high)+']. '+(r.coluna=='tipo_outros'?'Outros não é exclusivamente climático.':'')+' '+(r.delta_BIC_sem_exposicao>=0?'O modelo sem exposição tem BIC menor.':'O DLM da grade tem BIC menor que o comparador sem exposição.')+'</p><button data-selected-jump="'+esc(r.coluna)+'" data-selected-level="'+esc(r.nivel)+'">Explorar interpretação e perfil</button></article>').join('');
document.querySelectorAll('[data-selected-jump]').forEach(b=>b.onclick=()=>{$('sel-period').value='Total';$('sel-level').value=b.dataset.selectedLevel;selectedChoices();$('sel-exposure').value=b.dataset.selectedJump;selectedUpdate();document.querySelector('[data-current-tab=Nacional]').click();$('current-explore').scrollIntoView({behavior:'smooth'})});
table('current-joint',S.nacional.filter(r=>r.q_joint<.05),[['periodo','Período'],['exposicao','Categoria'],['K','K'],['p_proprio','AR'],['q_joint','q conjunto'],['q','q acumulado'],['diagnostico','Diagnóstico']]);table('sel-g-all',D.gm.filter(r=>r['p BH']!=null&&r['p BH']<.05),[['Período','Período'],['Exposição','Categoria'],['p BH','q BH'],['Triagem ampliada','Triagem ampliada'],['Motivos','Ressalvas']]);table('selected-manifest',S.manifest,[['fonte','Fonte'],['linhas','Linhas'],['sha256','SHA256']]);$('selected-validation').textContent=S.validacao.verificacoes+' verificações aprovadas; CR2 reconciliado com cinco contrastes R históricos. Bootstrap do painel com zero singularidades. Células do notebook 20 executadas sequencialmente em Python, com saídas gravadas.';
$('sel-export').onclick=()=>{let per=$('sel-period').value,col=$('sel-exposure').value;download(csv([...S.painel,...S.nacional].filter(r=>r.periodo==per&&r.coluna==col)),'dlm_defasagens_selecionadas.csv','text/csv;charset=utf-8')};selectedChoices();selectedUpdate();
'''
def build(destination,historical=None):
 import hashlib
 tables=ROOT/'outputs/tables/dlm_selecionado';payload={};manifest=[]
 for name in ['painel','nacional','painel_perfis','nacional_perfis','painel_candidatos','nacional_candidatos','cobertura']:
  p=tables/(name+'.csv');df=pd.read_csv(p);payload[name]=df.astype(object).where(pd.notna(df),None).to_dict(orient='records');manifest.append(dict(fonte='dlm_selecionado/'+p.name,linhas=len(df),sha256=hashlib.sha256(p.read_bytes()).hexdigest()))
 payload['manifest']=manifest;payload['validacao']=json.loads((tables/'validacao.json').read_text())
 if historical:base=Path(historical).read_text()
 else:base=old.HTML.replace('PAYLOAD',json.dumps(old.load(),ensure_ascii=False,allow_nan=False).replace('</','<\\/'))
 # The entire prior report is explicitly archived, including its older favourable highlights.
 base=base.replace('Resumo para apresentar à orientadora','Síntese dos resultados anteriores')
 base=re.sub(r'<header>.*?</header>','<header><div class="eyebrow">TCC • Isabella Viana Bambirra • revisão de defasagens</div><h1>Desastres e inadimplência: DLMs com janelas selecionadas</h1><p>Uma seleção por categoria e período, coeficientes livres em painel e nacional, resultados atuais e histórico separado. Granger preservado. Versão de 5 de outubro de 2026.</p></header>',base,count=1,flags=re.S)
 base=base.replace('</style>',CSS+'</style>',1)
 pos=base.index('<main>');base=base[:pos]+BODY+'<main><details id="historical-report" class="current-legacy"><summary>Análises anteriores preservadas — painel K10 e nacional com spline</summary><div class="current-warning"><b>Histórico:</b> todos os números e interpretações deste bloco pertencem à versão anterior à seleção de K por categoria. Não são os resultados atuais. Granger permanece válido como análise preservada. As robustezes e placebos antigos não validam automaticamente os novos modelos selecionados.</div>'+base[pos+len('<main>'):]
 base=base.replace('</main>\n<footer','</details></main>\n<footer',1) if '</main>\n<footer' in base else base
 # Close the archive at the last historical main, before data/scripts, without affecting current main.
 hstart=base.index('<details id="historical-report"');end=base.index('</main>',hstart)
 if not base[end-10:end].endswith('</details>'):base=base[:end]+'</details>'+base[end:]
 encoded=json.dumps(payload,ensure_ascii=False,allow_nan=False,separators=(',',':')).replace('</','<\\/')
 base=base.replace('</body>','<script id="selected-data" type="application/json">'+encoded+'</script><script>'+JS+'</script></body>',1)
 Path(destination).write_text(base);return destination
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--output',default=str(ROOT.parent/'relatorio_granger_dlm_integrado.html'));p.add_argument('--historical');a=p.parse_args();print(build(a.output,a.historical))
