"""HTML standalone com dados reais exportados, sem bibliotecas remotas."""
from pathlib import Path
import json,html
import pandas as pd
from dlm_painel_log import ROOT,OUT,FIG,slug

def records(name):return json.loads(pd.read_csv(OUT/(name+'.csv')).to_json(orient='records',force_ascii=False))
def build():
 data={n:records(n) for n in ['resultados','perfis','amostras_suporte','modelos','diagnosticos','estacionariedade_uf','taxonomia','cenarios','autocorrelacao_uf','influencia_uf','validacao','auditoria']}
 images={}
 for row in data['amostras_suporte']:
  p=FIG/(slug(row['periodo'])+'_'+row['exposicao']+'.svg')
  if p.exists():images[row['periodo']+'|'+row['exposicao']]=p.read_text()[p.read_text().find('<svg'):]
 decisions=(ROOT/'docs/dlm_painel_log_protocolo.md').read_text(); table=[]
 for line in decisions.splitlines():
  if line.startswith('|') and not line.startswith('|---'):table.append([html.escape(x.strip()) for x in line.strip('|').split('|')])
 dec='<table>'+''.join('<tr>'+''.join('<th>'+x+'</th>' if i==0 else '<td>'+x+'</td>' for x in row)+'</tr>' for i,row in enumerate(table))+'</table>'
 source=HTML.replace('__DATA__',json.dumps(data,ensure_ascii=False).replace('</','<\\/')).replace('__IMAGES__',json.dumps(images,ensure_ascii=False).replace('</','<\\/')).replace('__DECISIONS__',dec)
 p=ROOT/'outputs/reports/relatorio_dlm_painel_log.html';p.parent.mkdir(parents=True,exist_ok=True);p.write_text(source);return p
HTML=r'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DLM · Desastres e inadimplência</title><style>
:root{--ink:#20353e;--teal:#146c7c;--line:#dce6e9;--muted:#64747b;--bg:#f3f7f8;--amber:#925322}*{box-sizing:border-box}body{margin:0;background:var(--bg);font:16px/1.6 system-ui,sans-serif;color:var(--ink)}header{background:#102831;color:#f2fbfc;padding:52px max(6vw,24px)}header h1{font-size:clamp(32px,5vw,58px);line-height:1.12;max-width:900px;font-weight:650;margin:20px 0}header p{max-width:820px;color:#bdced3}.tag{font-size:12px;letter-spacing:.15em;text-transform:uppercase;color:#84d3d5}.pills{display:flex;gap:12px;flex-wrap:wrap}.pills span{border:1px solid #52717c;border-radius:22px;padding:6px 14px;font-size:13px}nav{position:sticky;top:0;background:#fff;border-bottom:1px solid var(--line);padding:12px 6vw;z-index:5;display:flex;gap:10px;flex-wrap:wrap}button{font:inherit;border:0;border-radius:8px;padding:8px 14px;background:#e9f0f2;color:var(--ink);cursor:pointer}button.active,button:hover{background:var(--teal);color:white}main{max-width:1240px;padding:26px 24px 70px;margin:auto}section{display:none}section.active{display:block}h2{font-size:30px;margin:10px 0 18px}h3{margin:0 0 12px;font-size:21px}p{margin:10px 0 18px}.card{background:white;border:1px solid var(--line);border-radius:14px;padding:24px;margin-bottom:20px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:16px}.metric{padding:20px;background:#fff;border:1px solid var(--line);border-radius:12px}.metric strong{display:block;font-size:28px;color:var(--teal)}.metric span,small{color:var(--muted);font-size:13px}.notice{border-left:4px solid #bd743f;background:#fff4e8;padding:18px 22px;margin:18px 0;border-radius:8px}.good{border-left-color:var(--teal);background:#e9f5f5}.eq{text-align:center;background:#eef5f7;border-radius:10px;padding:24px;font:20px/1.6 Georgia,serif;overflow-x:auto}.table{overflow:auto;max-height:520px}table{width:100%;border-collapse:collapse;font-size:13px}th{background:#eaf1f3;text-align:left;position:sticky;top:0;color:#365660}td,th{padding:10px 12px;border-bottom:1px solid var(--line);vertical-align:top}tr:hover td{background:#f5fafb}label{font-size:13px;font-weight:600}select{display:block;margin-top:5px;min-width:150px;width:100%;font:inherit;padding:10px;border:1px solid #b9cdd3;border-radius:8px;background:white}#plots svg{width:100%;height:auto}details{margin:12px 0}summary{cursor:pointer;color:var(--teal);font-weight:600}.filters{display:grid;grid-template-columns:180px 1fr 210px;gap:16px;margin:0 0 20px}.caption{color:var(--muted);font-size:13px}a{color:var(--teal)}footer{font-size:12px;color:var(--muted);margin-top:24px}@media(max-width:650px){.filters{grid-template-columns:1fr}.card{padding:18px}nav{position:static}main{padding:20px 14px}header{padding:35px 22px}}@media print{section{display:block!important}nav,.filters,button{display:none}header{color:black;background:white}.card{break-inside:avoid}}
</style></head><body><header><div class="tag">TCC · Estatística · UFSCar</div><h1>Desastres registrados e inadimplência:<br>associações ao longo dos meses</h1><p>Uma análise clássica de defasagens distribuídas em painel. A pergunta, as decisões, os resultados e os limites do modelo em uma leitura organizada.</p><div class="pills"><span>27 UFs</span><span>Δlog(I) · Δlog(1+D)</span><span>k = 0,…,6</span><span>06 outubro 2026</span></div><p><small style="color:#b8cdd4">Isabella Viana Bambirra<br>Versão atual de DLM · análise exploratória</small></p></header>
<nav><button data-tab="overview" class="active">Visão geral</button><button data-tab="method">Metodologia</button><button data-tab="data">Dados e classificação</button><button data-tab="analysis">Resultados interativos</button><button data-tab="station">Estacionariedade</button><button data-tab="conclusion">Conclusões e reprodução</button></nav><main>
<section id="overview" class="active"><h2>O que esta análise permite dizer</h2><div class="notice good"><b>O total climático não apresentou rejeição a 5% para a associação acumulada nos seis meses.</b> Isso ocorre nos dois recortes, tanto com erros agrupados por UF quanto na comparação Driscoll–Kraay. Não rejeição não comprova ausência de associação.</div><div class="grid"><div class="metric"><strong>37.643</strong><span>registros do total climático · COBRADE 12/13/14</span></div><div class="metric"><strong>2.106</strong><span>observações efetivas no pré · ago/2013–jan/2020</span></div><div class="metric"><strong>3.699</strong><span>observações efetivas no total · ago/2013–dez/2024</span></div><div class="metric"><strong>6 meses</strong><span>horizonte fixo, além do contemporâneo</span></div></div><div class="card" style="margin-top:20px"><h3>Por que a conclusão é condicionada</h3><p>Os diagnósticos de estacionariedade estaduais não são uniformes. Δlog(I) é inconclusiva em 19 UFs no pré e 8 no total; há evidência desfavorável em RO/SC no pré e RO no total. Isso impede apresentar o painel completo como validado.</p><p>Há correlação residual entre UFs. Cluster por UF admite correlação dentro do estado, mas não resolve essa dependência transversal. DK6 fornece uma comparação da inferência, com suas próprias limitações.</p></div><div class="card"><h3>Como navegar</h3><p>Leia a metodologia e a auditoria; depois selecione período e exposição em “Resultados interativos”. Cada visão reúne amostra, suporte, perfil de coeficientes, somas, testes, cenários e diagnósticos. A aba de estacionariedade mostra os testes por UF. Todos os dados e gráficos estão incorporados neste arquivo, que funciona offline.</p></div></section>
<section id="method"><h2>Uma estrutura de modelo</h2><div class="card"><h3>Equação estimada</h3><div class="eq">Δlog(I<sub>it</sub>) = α<sub>i</sub> + λ<sub>t</sub> + ∑<sub>k=0</sub><sup>6</sup> β<sub>k</sub> Δlog(1+D<sub>i,t−k</sub>) + ε<sub>it</sub></div><p>I é a taxa positiva de inadimplência PF, 100×carteira inadimplente/carteira ativa. D é a contagem de registros administrativos no estado e mês do evento. Os logs são naturais. Primeiro log, depois diferença: não é log da diferença.</p><p>MQO sem ponderação, efeitos fixos de UF e completos de mês-ano; nenhuma defasagem de Y. Um modelo separado por exposição, com todas as 27 UFs. Total, grupos e tipologias sobrepostos nunca entram juntos.</p><p>K=6 foi fixado antes da estimação como janela mensal de curto prazo para perdas de renda e transmissão à inadimplência. Não é um horizonte selecionado pelo p-valor ou pelo BIC, nem evidência de que o fenômeno termina em seis meses.</p></div><div class="card"><h3>Decisões, razões e consequências</h3><div class="table">__DECISIONS__</div></div><div class="card"><h3>Inferência e pressupostos</h3><p>CR1: G/(G−1)×(n−1)/(n−p<sub>total</sub>), com p<sub>total</sub>=G+T−1+7; t com 26 graus de liberdade e Wald F(r,26). DK6: scores agregados por mês, Bartlett com largura de seis meses, correção n/(n−p<sub>total</sub>), t(T−1) e F(r,T−1). A comparação DK depende de aproximação em T grande e da largura escolhida.</p><p>Normalidade e homocedasticidade não são requisitos universais da consistência do MQO com inferência robusta. Exogeneidade estrita exige E[ε<sub>it</sub>|X<sub>i1</sub>,…,X<sub>iT</sub>,α<sub>i</sub>,{λ<sub>s</sub>}]=0. A origem natural não garante essa condição. Os coeficientes vêm da variação residual após ambos os efeitos fixos.</p><p>BH é aplicado por período, nível de exposição, covariância e endpoint. Uma categoria indisponível não recebe p calculado: p=1 serve apenas ao ajuste conservador da família. IC das curvas são pontuais, sem cobertura simultânea.</p></div><div class="card"><h3>Correções do capítulo</h3><p>Almon não foi necessário: o DLM irrestrito tem posto completo nas aplicações estimadas. A fórmula clássica, se usada futuramente, é Z<sup>(0)</sup>=∑<sub>k=0</sub><sup>K</sup>x<sub>t−k</sub> e Z<sup>(j)</sup>=∑<sub>k=0</sub><sup>K</sup>k<sup>j</sup>x<sub>t−k</sub>, j≥1. β<sub>k</sub>=∑a<sub>j</sub>k<sup>j</sup>, com V<sub>β</sub>=BV<sub>a</sub>B′. Potências brutas não garantem menor correlação entre regressores.</p><p>A soma é “efeito acumulado no horizonte K”. Não é automaticamente um efeito causal de longo prazo, nem a resposta a um único desastre físico.</p></div></section>
<section id="data"><h2>O que os registros representam</h2><div class="card"><h3>Crédito e calendário</h3><p>3.888 células UF-mês, chave única, 27 UFs e 144 meses consecutivos. Carteiras e taxa positivas, com TI reconciliada à razão 100CI/CA. Nenhum dado de crédito ausente foi substituído por zero. Diferenças e lags são feitos dentro de UF e recorte, com perda de sete meses iniciais por UF.</p><h3>Atlas e identificação</h3><p>40.339 linhas no recorte, 40.339 protocolos distintos. Identificador auditável: hash SHA256 do CSV e número da linha original, com cabeçalho na linha 1. Agregação por UF e mês de Data_Evento. As 101 repetições da chave UF/município/data/COBRADE permanecem na medida A. B e cobertura municipal são medidas históricas, sem uma nova bateria de estimações.</p><p>Registros não equivalem a eventos físicos únicos, intensidade, área ou população afetada. Zero é ausência de linha na fonte reconciliada; subnotificação e regras administrativas podem afetar a medida.</p><div class="notice">O total central seleciona COBRADE 12/13/14 diretamente. Geológicos ficam fora, mesmo quando chuva pode ser um gatilho; biológicos e tecnológicos também. “Outros”, doenças infecciosas e barragens não são exclusivamente climáticos.</div></div><div class="card"><h3>Classificação original e mapeamento analítico</h3><p>As inconsistências de nomes ficam visíveis. O código 13310 é onda de calor, mas aparece em Chuvas Intensas; 13120 é frente fria/zona de convergência em Onda de Frio; 14140 é baixa umidade. Mantemos os rótulos originais em cada aplicação e selecionamos o central pelos códigos.</p><div id="taxonomy" class="table"></div><p class="caption">Fonte de referência: <a href="https://www.defesacivil.pr.gov.br/sites/defesa-civil/arquivos_restritos/files/documento/2022-10/cobrade.pdf">Tabela COBRADE · Defesa Civil do Paraná</a>. Classificação analítica não atribui os registros ao aquecimento antropogênico.</p></div></section>
<section id="analysis"><h2>Resultados por período e exposição</h2><div class="filters"><label>Período<select id="period"><option>Pré</option><option>Total</option></select></label><label>Exposição<select id="exposure"></select></label><label>Covariância<select id="cov"><option value="CR1">Cluster por UF · CR1</option><option value="DK6">Driscoll–Kraay · 6 meses</option></select></label></div><div id="sample" class="grid"></div><div id="interpret" class="notice"></div><div class="card"><h3>Perfil incremental e resposta acumulada</h3><p>β<sub>k</sub> relaciona uma mudança logarítmica dos registros a uma mudança logarítmica da taxa k meses depois, condicionada aos outros lags e FE. C(h)=∑<sub>k=0</sub><sup>h</sup>β<sub>k</sub> acumula essa resposta em log(I) a um pulso unitário em Δlog(1+D).</p><div id="plots"></div><p class="caption">Unidades logarítmicas, sem pontos percentuais. Faixas IC95% pontuais; comparar CR1 e DK6 não significa escolher o menor p.</p></div><div class="card"><h3>Contemporâneo, somas e testes conjuntos</h3><p>β0 é contemporâneo; soma0K inclui k=0; soma1K isola os lags 1 a 6. O conjunto pode rejeitar mesmo se a soma não rejeita, porque coeficientes com sinais opostos se compensam. A variância das somas inclui todas as covariâncias: c′Vc.</p><div id="results" class="table"></div><button id="download">Baixar resultados da visão · CSV</button></div><div class="card"><h3>Coeficientes por defasagem</h3><div id="coeff" class="table"></div></div><div class="card"><h3>Traduzir um contraste sem mudar a unidade</h3><p>Contraste ilustrativo 0→1 registro: δx=log(2). Um aumento persistente de D gera um pulso na diferença; um aumento de D por um único mês gera +log2 e −log2 no mês seguinte. Aplicamos a convolução com β e acumulamos em log(I). A variação relativa da taxa é 100×[exp(resposta acumulada)−1].</p><div id="scenario" class="table"></div><p class="caption">Cenários algébricos condicionais, sem atribuição causal. Variação relativa percentual da taxa, não pontos percentuais de inadimplência. Um registro administrativo não identifica um evento físico único.</p></div><div class="card"><h3>Suporte, identificação e resíduos</h3><p>Os modelos mantêm estados com zero exposição. A exposição concentrada pode ter muito menos suporte efetivo do que os 27 clusters sugerem. VIF e condição usam a matriz após remover os FE. Ljung–Box e Levene são diagnósticos descritivos; p-valores isolados não validam a especificação.</p><div id="diag" class="table"></div><div id="support" class="table"></div><details><summary>Influência e autocorrelação por UF</summary><div id="influence" class="table"></div><div id="lb" class="table"></div></details></div></section>
<section id="station"><h2>Estacionariedade: evidência e inconclusão</h2><div class="card"><h3>As hipóteses dos dois testes</h3><div class="eq">ADF: Δz<sub>t</sub>=c+γz<sub>t−1</sub>+∑φ<sub>j</sub>Δz<sub>t−j</sub>+u<sub>t</sub><br>H<sub>0</sub>: γ=0 · raiz unitária &nbsp; H<sub>1</sub>: γ&lt;0</div><div class="eq" style="margin-top:12px">KPSS: z<sub>t</sub>=c+r<sub>t</sub>+u<sub>t</sub>, r<sub>t</sub>=r<sub>t−1</sub>+η<sub>t</sub><br>H<sub>0</sub>: Var(η)=0 · estacionariedade em torno do intercepto<br>H<sub>1</sub>: Var(η)&gt;0</div><p>ADF usa intercepto, AIC e máximo min(12, regra Schwert admissível). KPSS usa intercepto e banda automática. Se houvesse tendência, a hipótese seria em torno da tendência. p KPSS=0,10 significa p≥0,10 e p=0,01 significa p≤0,01.</p><table><tr><th>ADF</th><th>KPSS</th><th>Leitura a 5%</th></tr><tr><td>rejeita</td><td>não rejeita</td><td>favorável, sem certificação</td></tr><tr><td>não rejeita</td><td>não rejeita</td><td>inconclusivo</td></tr><tr><td>não rejeita</td><td>rejeita</td><td>desfavorável</td></tr><tr><td>rejeita</td><td>rejeita</td><td>divergente</td></tr></table></div><div class="notice">A mesma transformação mantém a definição da variável. Ela não resolve inconclusão, raízes unitárias, dependência transversal ou mudanças na dinâmica. A evidência desfavorável limita a regressão completa à leitura exploratória; não se pressupõe cointegração.</div><div class="card"><h3>Diagnósticos estaduais da visão selecionada</h3><p>Esta tabela acompanha o período e a exposição escolhidos em “Resultados interativos”; mostra y=Δlog(I) e x=Δlog(1+D), separadamente em cada UF. Séries constantes e testes indisponíveis ficam registrados.</p><div id="stationtable" class="table"></div><details><summary>Estatísticas, valores críticos e avisos completos</summary><div id="stationfull" class="table"></div></details></div><div class="card"><h3>Nacional e painel histórico não se confundem</h3><p>O diagnóstico nacional informado no pedido (intercepto/AIC): Δlog(I), pré ADF≈0,343 e KPSS≥0,10, inconclusivo; total ADF≈0,021 e KPSS≥0,10, favorável. Esses valores são referências fornecidas, não uma reexecução nacional nesta revisão.</p><p>O CIPS histórico avaliou I/ΔI e exposições em cobertura municipal. Ele foi preservado como histórico, mas não comprova estacionariedade das novas diferenças logarítmicas. Testes estaduais separados também não substituem um teste de painel que considere dependência transversal.</p></div></section>
<section id="conclusion"><h2>O que foi encontrado e como interpretar</h2><div class="card"><h3>Resultado central</h3><p>No pré, soma0:6=0,002709, IC95% cluster [−0,006075;0,011493], p=0,532. No total, 0,004372, IC [−0,001265;0,010009], p=0,123. DK6 fornece p=0,455 e 0,056, respectivamente. A família central tem uma aplicação por período, portanto q=p.</p><p>Não há rejeição acumulada a 5%, sem prova de ausência. Os períodos são sobrepostos; p diferentes não demonstram mudança temporal. O sinal positivo estimado não basta para concluir aumento da inadimplência.</p><h3>Aplicações complementares</h3><p>Movimento de Massa no total rejeita a soma após BH/CR1 (q≈0,0045), mas não após BH/DK6. A categoria é geológica e fica fora do total climático central. Há rejeições contemporâneas e conjuntas em categorias; a tabela abaixo preserva todas, com suporte e ressalvas. Elas não demonstram associação acumulada robusta do total climático.</p><div id="discoveries" class="table"></div></div><div class="card"><h3>Limites para a monografia</h3><p>Desenho observacional, exposição administrativa sujeita a subnotificação, coeficientes comuns entre UFs, K fixo de seis meses, estacionariedade não sustentada em todas as séries e dependência residual. Não identificar efeito causal sem hipóteses adicionais. Não atribuir registros às mudanças climáticas antropogênicas.</p><p>A associação temporal do DLM, a precedência preditiva de Granger e a causalidade são conceitos diferentes. Granger foi preservado; não houve SARIMAX.</p></div><div class="card"><h3>Reprodução e histórico</h3><p>Notebook 22 executado, código independente e tabelas em outputs/tables/dlm_painel_log. Manifesto registra hashes das duas entradas e do capítulo, versões e saídas. Gráficos em outputs/figures/dlm_painel_log. Validação compara FWL com MQO explícito, covariância CR1, DK com statsmodels e variância da soma.</p><div id="validation" class="table"></div><p>O histórico permanece nas branches analise/dlm, analise/dlm-revisao-metodologica, analise/dlm-validacao-final e analise/dlm-classico-1a10, com SHAs documentados. Somente esta revisão é incorporada à main.</p><p><a href="https://github.com/bellaviana4-cyber/TCC-analise_mudancas_climaticas_e_inadimplencia">Repositório do TCC</a> · Consulte docs/dlm_painel_log_protocolo.md e docs/dlm_painel_log_resultados.md.</p></div></section><footer>Relatório standalone · dados efetivamente calculados · IC95% pontuais · associação condicionada ao modelo e às hipóteses.</footer></main>
<script>const D=__DATA__, IMG=__IMAGES__;
const $=id=>document.getElementById(id),esc=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fmt(x){return x===null||x===undefined?'—':typeof x==='number'?(Number.isInteger(x)?x.toLocaleString('pt-BR'):x.toLocaleString('pt-BR',{maximumFractionDigits:6})):esc(x)}
function table(id,rows,cols){$(id).innerHTML=rows.length?'<table><thead><tr>'+cols.map(c=>'<th>'+esc(c[1])+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>'<td>'+fmt(r[c[0]])+'</td>').join('')+'</tr>').join('')+'</tbody></table>':'<p>Não disponível nesta aplicação; consulte o suporte e o status.</p>'}
const exposures=[...new Map(D.amostras_suporte.map(r=>[r.exposicao,r])).values()];$('exposure').innerHTML=exposures.map(r=>`<option value="${esc(r.exposicao)}">${esc(r.nivel+' · '+r.rotulo)}</option>`).join('');
let current=[];
function render(){let per=$('period').value,e=$('exposure').value,cov=$('cov').value;const keep=r=>r.periodo===per&&r.exposicao===e;let s=D.amostras_suporte.find(keep),r=D.resultados.filter(x=>keep(x)&&x.covariancia===cov);current=r;let sum=r.find(x=>x.endpoint==='soma0K'),p=D.perfis.filter(x=>keep(x)&&x.covariancia===cov),diag=D.diagnosticos.filter(keep);$('sample').innerHTML=[['N efetivo',s.N_efetivo],['UFs no painel',s.UFs_modelo],['UFs expostas · janela',s.ufs_expostas],['UF-mês positivos · janela',s.uf_mes_positivos]].map(x=>'<div class="metric"><strong>'+fmt(x[1])+'</strong><span>'+x[0]+'</span></div>').join('');
$('interpret').innerHTML='<b>'+esc(s.rotulo)+' · '+esc(per)+'</b><br>'+esc(s.suporte)+'. '+(sum?.status==='calculado'?'Efeito acumulado: '+fmt(sum.estimate)+'; p nominal='+fmt(sum.p)+'; q BH='+fmt(sum.q_BH)+'. '+(sum.q_BH<.05?'Rejeição na família desta covariância; verificar a comparação de inferência e os diagnósticos.':'Sem rejeição na família a 5%; não prova ausência de associação.'):'Sem inferência: '+esc(sum?.status||'indisponível'))+'<br>Unidade logarítmica. Estimativa exploratória, sem validade conclusivamente verificada. '+(e==='total_climatico'?'': 'Rótulo Atlas complementar; sua classificação não é necessariamente exclusivamente climática.');
$('plots').innerHTML=IMG[per+'|'+e]||'<p>Perfil não estimado por falta de suporte ou identificação.</p>';
table('results',r,[['endpoint','Contraste/teste'],['estimate','Estimativa (ou F)'],['se','Erro padrão'],['low','IC95% inferior'],['high','IC95% superior'],['df','df denominador'],['p','p nominal'],['q_BH','q BH'],['status','Status']]);
table('coeff',p,[['lag','Lag'],['beta_estimate','βk'],['beta_low','IC inferior'],['beta_high','IC superior'],['beta_p','p nominal descritivo'],['C_estimate','C(h)'],['C_low','IC C inferior'],['C_high','IC C superior']]);
table('scenario',D.cenarios.filter(x=>keep(x)&&x.covariancia===cov),[['cenario','Cenário'],['h','Mês h'],['resposta_delta_log_I','Resposta Δlog(I)'],['resposta_log_I_acumulada','Resposta log(I) acumulada'],['variacao_relativa_I_pct','Variação relativa I (%)'],['low_pct','IC inferior (%)'],['high_pct','IC superior (%)']]);
table('diag',diag,[['rho_abs_media','Correlação residual absoluta média'],['rho_max','Máxima'],['max_VIF','VIF máximo'],['max_cor_lags','Correlação máxima lags'],['maior_influencia_uf','Célula influente · UF'],['maior_influencia_data','Data'],['sd_residuo','Desvio dos resíduos']]);
table('support',[s],[['N_janela','N janela'],['N_efetivo','N efetivo'],['primeira_equacao','Primeira equação'],['ultima_equacao','Última equação'],['registros','Registros janela'],['N_eff','N efetivo exposição janela'],['top1','Share top1 janela'],['top2','Share top2 janela'],['efetivo_ufs_expostas','UFs expostas efetivo'],['efetivo_N_eff','N efetivo exposição amostra'],['efetivo_top1','Share top1 efetivo'],['efetivo_suporte','Suporte efetivo']]);
table('influence',D.influencia_uf.filter(keep).sort((a,b)=>b.share_variancia_acumulado-a.share_variancia_acumulado),[['uf','UF'],['share_variancia_acumulado','Share score² soma'],['N_eff_scores','N efetivo scores']]);
table('lb',D.autocorrelacao_uf.filter(keep),[['uf','UF'],['lag','Lag teste'],['LB','Ljung–Box'],['p','p diagnóstico']]);
let st=D.estacionariedade_uf.filter(x=>x.periodo===per&&(x.exposicao===e||x.exposicao==='inadimplencia'));
table('stationtable',st,[['exposicao','Série'],['uf','UF'],['n','N'],['ADF_estatistica','ADF estatística'],['ADF_p','ADF p'],['ADF_lag','ADF lag'],['KPSS_estatistica','KPSS estatística'],['KPSS_p','KPSS p tabela'],['KPSS_limite','Limite p KPSS'],['KPSS_lag','Banda'],['classificacao','Leitura'],['status','Status']]);
table('stationfull',st,Object.keys(D.estacionariedade_uf[0]).map(k=>[k,k]));}
for(let id of ['period','exposure','cov'])$(id).addEventListener('change',render);
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab],section').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});
table('taxonomy',D.taxonomia,[['descricao_tipologia','Tipologia Atlas'],['codigo','COBRADE'],['grupo_de_desastre','Grupo Atlas'],['grupo_COBRADE','Grupo COBRADE'],['registros','Registros'],['incluido_total_climatico','Central?'],['observacao','Observação']]);
table('validation',D.validacao,[['periodo','Período'],['coef_FWL_dummies_max_diff','Diferença coeficientes'],['cov_CR1_dummies_max_diff','Diferença CR1'],['DK_statsmodels_max_diff','Diferença DK'],['var_soma','Variância soma'],['passou','Passou']]);
let discoveries=D.resultados.filter(r=>r.q_BH<.05).map(r=>({...r,suporte:D.amostras_suporte.find(s=>s.periodo===r.periodo&&s.exposicao===r.exposicao)?.suporte}));table('discoveries',discoveries,[['periodo','Período'],['rotulo','Exposição'],['covariancia','Covariância'],['endpoint','Endpoint'],['estimate','Estimativa/F'],['p','p nominal'],['q_BH','q BH'],['suporte','Suporte janela']]);
$('download').onclick=()=>{let keys=Object.keys(current[0]||{}),quote=x=>'"'+String(x??'').replace(/"/g,'""')+'"',csv='\ufeff'+[keys.map(quote).join(';'),...current.map(r=>keys.map(k=>quote(r[k])).join(';'))].join('\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='dlm_'+$('period').value+'_'+$('exposure').value+'_'+$('cov').value+'.csv';a.click();URL.revokeObjectURL(url)};render();
</script></body></html>'''
if __name__=='__main__':print(build())
